version: '3.9'
networks:
  traefik:
    driver: bridge
services:
  traefik:
    image: traefik:2.6
    container_name: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--log.level=debug"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443" # new
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # new
      # - "--certificatesresolvers.myresolver.acme.email=your@email.com" # new
      # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" # new
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
